pcl_grid_map_extraction:
  num_processing_threads: 2
  cloud_transform:
    is_apply_rigidbody_trans: false
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation: #intrinsic rotation X-Y-Z (r-p-y)sequence
      r: 0.0
      p: 0.0
      y: 0.0
  cluster_extraction:
    cluster_tolerance: 0.05
    min_num_points: 1
    max_num_points: 1000000
  outlier_removal:
    is_remove_outliers: true
    mean_K: 8
    stddev_threshold: 0.1
  downsampling:
    is_downsample_cloud: true
    voxel_size:
      x: 0.05
      y: 0.05
      z: 0.05
  grid_map:
    min_num_points_per_cell: 2
    resolution: 0.1
    # 0: Smallest value among the average values ​​of each cluster
    # 1: Mean value of the cluster with the most points
    height_type: 1
    # For height_type 1
    height_thresh: 1.0